### ISSUE TITLE
Update 311 roadmap with April May & June changes

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-projects#45]
- [x] 311 roadmap has had community-driven updates, put them in the working roadmap.
- [x] Align completed work from the working roadmap and the public roadmap.

## New community stories

- [x] As a resident I want the City and my Alderman to provide me data on the needs of our community and the City's performance, so I can judge for myself if the city is providing equitable services.
- [x] As a resident, I want to add pictures to the subcategories, so I can easily understand the category.
- [x] As a resident, I want to check my status by open or close, so I can view only the active service request.
- [x] As a resident, I want to be able to edit my request or be told I cannot edit and directed to create a new request.
- [x] As a resident, I want call to action buttons in all knowledge articles, so I can create a service request without navigating out of the article.
- [x] As a resident, I want transparency on the status of my request and the ability to customize how I receive updates (phone, text, email, notification).
- [x] As a resident, I want confirm a service request has been fulfilled, so I can verify, or dispute & get it complete to my satisfaction.
